# py-lz4framed (Iotic Labs)

{% set name = "py-lz4framed" %}
{% set version = "0.11.0" %}
{% set sha256 = "4507ab475a3965b9cb75b5ebe2f86afcbf6472d036417e4d0a0bdd205418e494" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
  run:
    - python

test:
  source_files:
    - test.py

about:
  home: https://github.com/Iotic-Labs/py-lz4framed
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'LZ4Frame library for Python (via C bindings)'
  description: |
    This is an LZ4-frame compression library for Python v3.2+ (and 2.7+),
    bound to Yann Collet's LZ4 C implementation.
  doc_url: https://github.com/Iotic-Labs/py-lz4framed
  dev_url: https://github.com/Iotic-Labs/py-lz4framed

extra:
  recipe-maintainers:
    - vtermanis
    - timchurchard
