appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: TkQrjmdtXYq8yAg+1C4at+BGZ+YLB7SN9FXTSLuHaH+uMVWyCM+VgdSodATMSGisWZ4B8H2JvmtnNt8zHq7PsTmGIDu7aP9UBAx9rKSA3w3ekY7s0gCemKEyyL6qQbjmEB1ICf5VKmwfvHs/Lu5bamcVNVuQfTiXEw4enUoTiL/ZmTzBz5djPp7rUD2Q8VcHSpekbIe2MPuUihL4nqYXHDO/aSV0A9jceHQpnUVT1sDlZ/WLUyMsaqyHmGw2QA9bX3PyXZ7DN6Q+aUV/oH+MW+bV2ST6uLbeXItT1uqy7j5Y2x1QCRIZrRWIgT6XbrLCoXREqgd7bt2Ebnilf5zIPxxyXvnw0dB45WiwMMA5Bk44nyZPYKP6GP8rzzza6qyZz13VnqDXfg0yIH0rMxjMc6rLxRoBBJ8Y8/vkb3bdZhC8CG0xGTdL/26bdb0FW1Wq9LI6pBu31i5kDhLQkV5uMUJCA/94CFl0Uj3MHdDzcY7+ii3zNsNGlIPRHrR/pcXgBGnTIaWmtkNshYMvUf0kv25j4jjCXgernR5JYgYNaXE8LgxCzPxSt5mIr521zYXHH9agDZmRzItJyS8yxW2iKLeDvDUvBCmbeo3rGClf19qdNp1SeQgFTzmzwtpRCSTtQx9B7pW9PoFc8g77bGGH3j8E14HLlJJ2AAWcYOcaDt8=}
