travis:
  secure:
    BINSTAR_TOKEN: bS/f4BG/DhTGkKRw13xmXnl2q2d1xjp0yQJETHP14mFZLoHtUaak9a/P60IPKB7ae1o4MvYUV0DhV2Rvz7MrrOTaLLmKXN/HHeB02e8YL+1QsZFFJkrToUstwKriaFUu58On8TfIprTkB3iQn9ErvZz70uOMnwlGtlHuAbbeA98YYXOFQEQzD0dR8+t0SiJJFu/5UNnlBTgNy0ok/Kj5sKlK8PyHUeTgDRiLyvwmG8N5KmgHp1kAMqr0n83fAGPmKtiQcJl2oZpCFAafgZpD6uj/ZZ7m0tpwTqW7tuJYtvn+VZhbzRg/MohAgLrkWtwt+0zoctcGTgw6QpgnDOY/m3IYnozPIq/b4uwjdMUzwJjBK+PESqNxd/tvYxuJYx8PjQecMgEUeSod4LzzXc6ocUmGxnAXpgV1T0NYJRRxjp6ktd7inpXGxZeUBWZT3H147bNPZFgDXThbc0BviXnw0h1LxtuumszzMi3nkQ70HVyHq//r7Gip31Ty9gziKQgzgJXSXxw79Yxz49lw1Xpfy1dHFw2L/Duyd3n0eIqMeVZ33BV03BIQse+LS1VYBhRLnePj0J1ZUo0HvAighEK/t9p0E2+yKLhK7LHGfES5vWYBBBSqo8OahR8lh2o+K8JS1uALerziFGxN1TjlOhiPr/o657LeLJM0NakxH2c0+zw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
